services:
  mlflow:
    image: salahgo/mlflow:v4
    container_name: mlflow
    working_dir: /mlflow
    command: >
      mlflow server --host 0.0.0.0 --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --artifacts-destination s3://mlops12012026/mlflow-artifacts
    ports:
      - "5000:5000"
    volumes:
      - mlflowdata:/mlflow
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

  iris-api:
    image: ghcr.io/helabhl/mlops-project:latest
    container_name: iris-api
    ports:
      - "5001:5001"
  
  zenml-db:
    image: mysql:8.0
    container_name: zenml-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: zenmlroot
      MYSQL_DATABASE: zenml
      MYSQL_USER: zenml
      MYSQL_PASSWORD: zenmlpass
    volumes:
      - zenmlmysqldata:/var/lib/mysql

  zenml-server:
    image: zenmldocker/zenml-server:latest
    container_name: zenml-server
    restart: unless-stopped
    depends_on:
      - zenml-db
    ports:
      - "8080:8080"
    environment:
      ZENML_STORE_URL: mysql://zenml:zenmlpass@zenml-db:3306/zenml
      ZENML_DEFAULT_USER_NAME: hela
      ZENML_DEFAULT_USER_PASSWORD: Zenml123*

volumes:
  mlflowdata: {}
  zenmlmysqldata: {}

