name: Build and Deploy to AWS EC2

on:
  push:
    branches: ["main", "test-deploy"]

env:
  IMAGE_NAME: ghcr.io/helabhl/mlops-project:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./iris_api
          file: ./iris_api/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Login Docker sur EC2
            echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Créer le dossier de l'app si pas existant
            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app

            # Arrêter et supprimer l'ancien conteneur si existant
            docker stop iris_api || true
            docker rm iris_api || true

            # Pull de la nouvelle image
            docker pull ${{ env.IMAGE_NAME }}

            # Lancer le conteneur sur le port 5001
            docker run -d -p 5001:5001 --name iris_api ${{ env.IMAGE_NAME }}
